inherit_gem:
  rubocop-govuk:
    - config/default.yml

inherit_mode:
  merge:
    - Exclude

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'spec/**/*.rb'
    - 'lib/tasks/**/*.rake'
