# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c99a4935cb34b86f1776fad43bd209465e81924bfd44bcbd544c459f5fc75f78128cc4119dbfee2f7549c61780e2b2c2d89f7f06c7b40c8abfa29812ce49810a

test:
  secret_key_base: 2f665b76d63946fdbb0d7f33223153eebdadab4928bf3f909a4e73595dea22f8ce78c19ea7b64292ba39145176ab4d9583d4b03df8dac2d380321b29a0cf150b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  notify_api_key: <%= ENV["GOVUK_NOTIFY_API_KEY"] %>
